config/routes.rb
Rails.application.routes.draw do
  post '/check_weather', to: 'home#check_weather'
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :validate_address, only: [:check_weather]

  def index
  end

  # check weather with OpenWeather Client
  def check_weather
    if @address_service.postal_code.present?
      @weather_service = WeatherCheckService.new(@address_service)

      respond_to do |format|
        format.js { render action: 'index' }
      end
    else
      flash[:error] = 'The Address entered is invalid. Please enter a valid address'
      redirect_to root_path
    end
  end

  # validate address with Geocoder
  def validate_address
    @address_service = AddressCheckService.new(params[:input_address][:address])
  end

  attr_reader :address_service
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_weather_results.html.erb
<div class="results-page">
  <strong>Address Entered: </strong><%= @address_service.formatted_address %>
  <br>
  <br>
    <strong>Current Temperature: </strong><%= @weather_service.current_temp %>
    <br>
    <br>
    <strong>Low: </strong><%= @weather_service.low_temp %>
    <br>
    <br>
    <strong>High: </strong><%= @weather_service.high_temp %>
    <br>
    <br>
    <strong>Extended 8-day forecast: </strong><%= @weather_service.extended_forecast %>
    <br>
    <br>
    Cached? - <%= @weather_service.cached? %>
</div>

app/views/home/index.html.erb
<%= form_for :input_address, remote: true, :url => check_weather_path do |f| %>
  <%= f.label "Enter address to check weather" %>
  <br>
  <%= f.text_field :address %>
  <%= f.submit "Check" %>
<% end%>
<br>
<div id='weather_results'>
</div>

app/views/home/index.js.erb
$('#weather_results').html("<%= j render 'weather_results' %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </body>
</html>